### PR TITLE
Added Apple Support

### PR DESCRIPTION
**Pull request by olivia-banks**
Added Apple Support.
Sorry about me not getting to this. I added the declaration and then subsequently forgot to make a pull request. 
I've skimmed over the code base and found nothing that shouldn't work with Mac OS.
#55

### CODE REVIEW

**Comment by end2endzone** [comment]
Hi. No problem here. As we do say here: "Better late than never". I will take a look at your changes.

**Review by end2endzone — COMMENTED** [review]
Hi.
I have looked at your change. 

I don't want to sound rude but adding a `__LINUX__` preprocessor in a macOS environment... is this common behavior ? I was expecting to see preprocessor directive such as `#elif __linux__` to be replaced by `#elif defined(__linux__) || defined(__APPLE__)`. I understand that adding the preprocessor `__LINUX__` is easier and does not requires changing the code but I am concerned at long term here. Eventually, if we do end up with code that must be compiled differently on macOS and linux, than `__linux__` will be "true" in both environments.

Also the code uses `__linux__` (lower case) but your change is upper case, does your compiler on macOS sees `__LINUX__` and `__linux__` as identical?

Note that these observations are only for a discussion. I am more than happy that someone else is contributing to this project. You know much better than me what is considered "best practices" on macOS than me.

**Comment by olivia-banks** [comment]
Oh, sorry! I must've made a pull request for the wrong commit, or committed the other code to a different repo or some. I was just curious to see if it would work, with the __LINUX__ on Mac. 👍 

Thanks, I'll work on getting you the other code.

**Comment by end2endzone** [comment]
hehehe. No problem. It happens all of us. If you can't add more commits to this pull request, just tell me and I will close it and you will be able to open a new one.

**Comment by end2endzone** [comment]
Have you find where you committed your changes ? Do you plan to push more changes to this PR? I do plan to enable Github Actions to support building on Linux, Windows and eventually Mac.

**Pull request merged**
